version: '3.8'

services:
  api:
    build: .
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --workers 1
      --timeout-keep-alive 75
      --timeout-graceful-shutdown 30
      --proxy-headers
      --forwarded-allow-ips "*"
      --no-access-log
      --no-server-header
      --limit-concurrency 1000
      --backlog 2048
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - telegram_sessions:/app/sessions
      - logs:/app/logs
    environment:
      - TZ=UTC
      - ENVIRONMENT=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rest-tg.rule=Host(`rest-tg.redevest.ru`)"
      - "traefik.http.routers.rest-tg.entrypoints=websecure"
      - "traefik.http.routers.rest-tg.tls=true"
      - "traefik.http.routers.rest-tg.tls.certresolver=cloudflare"
      - "traefik.http.services.rest-tg.loadbalancer.server.port=8000"
    networks:
      - traefik-public
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    stop_grace_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traefik-public:
    external: true

volumes:
  telegram_sessions:
    name: rest_tg_sessions
  logs:
    name: rest_tg_logs
