services:
  api:
    build: .
    expose:
      - "8000"
    volumes:
      - telegram_sessions:/app/sessions
      - logs:/app/logs
    env_file:
      - .env
    environment:
      - TZ=UTC
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rest-tg.rule=Host(`rest-tg.redevest.ru`)"
      - "traefik.http.routers.rest-tg.entrypoints=websecure"
      - "traefik.http.routers.rest-tg.tls=true"
      - "traefik.http.routers.rest-tg.tls.certresolver=cloudflare"
      - "traefik.http.services.rest-tg.loadbalancer.server.port=8000"
    networks:
      - traefik-public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    stop_grace_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traefik-public:
    external: true

volumes:
  telegram_sessions:
    name: rest_tg_sessions
  logs:
    name: rest_tg_logs
