services:
  api:
    build: .
    expose:
      - "8000"
    volumes:
      - telegram_sessions:/app/sessions
      - logs:/app/logs
      - .env:/app/.env:ro
    environment:
      - TZ=UTC
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`rest-tg.redevest.com`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
    networks:
      - traefik-public
    healthcheck:
      test: ["CMD", "python", "-c", "import http.client; conn = http.client.HTTPConnection('localhost:8000'); conn.request('GET', '/health'); response = conn.getresponse(); exit(0 if response.status == 200 else 1)"]
      interval: 60s
      timeout: 5s
      retries: 2
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    stop_grace_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traefik-public:
    external: true

volumes:
  telegram_sessions:
    name: rest_tg_sessions
  logs:
    name: rest_tg_logs
